blackowl_sylius_um_admin_ajax:
    resource: "@BlackowlSyliusUmPlugin/Resources/config/routing/admin/ajax.yaml"
    prefix: /ajax

blackowl_sylius_um_admin:
    resource: |
        alias: blackowl_sylius_um.um
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: blackowl_sylius_um_admin_um
        vars:
            all:
                subheader: blackowl_sylius_um.ui.um
                templates:
                    form: "@BlackowlSyliusUmPlugin/Admin/Um/_form.html.twig"
            index:
                icon: 'file image outline'
    type: sylius.resource