blackowl_sylius_supplier_shop_supplier_show:
    path: /supplier/{code}
    methods: [GET]
    defaults:
        _controller: blackowl_sylius_supplier.controller.supplier:showAction
        _sylius:
            repository:
                method: findOneByCode
                arguments:
                    - $code
