sylius_grid:
    templates:
        action:
            um_product_list: "@BlackowlSyliusUmPlugin/Grid/Action/umProductList.html.twig"
    grids:
        blackowl_sylius_um_admin_um:
            driver:
                name: doctrine/orm
                options:
                    class: "%blackowl_sylius_um.model.um.class%"
            sorting:
                name: asc
            fields:
                code:
                    type: string
                    label: blackowl_sylius_um.ui.code
                    sortable: ~
                name:
                    type: string
                    label: blackowl_sylius_um.ui.name
                    sortable: ~
                
            filters:
                search:
                    type: string
                    options:
                        fields: [code, name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
