sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                um:
                    type: twig
                    label: blackowl_sylius_supplier.ui.supplier
                    options:
                        template: "@BlackOwlSyliusUmPlugin/Grid/Field/um.html.twig"
            filters:
                supplier:
                    type: entity
                    label: blackowl_sylius_supplier.ui.supplier
                    form_options:
                        class: "%blackowl_sylius_um.entity.productUm.class%"
