sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                um:
                    type: twig
                    label: blackowl_sylius_um.ui.um
                    options:
                        template: "@BlackowlSyliusUmPlugin/Grid/Field/um.html.twig"