imports:
    - "@BlackOwlSyliusUmPlugin/Resources/config/grids/blackowl_sylius_productUm_admin_um.yaml"

jms_serializer:
    metadata:
        directories:
            blackowl-sylius-um:
                namespace_prefix: "BlackOwl\\SyliusUmPlugin\\Model"
                path: "@BlackOwlSyliusUmPlugin/Resources/config/serializer"
