imports:
    - "@BlackowlSyliusUmPlugin/Resources/config/grids/blackowl_sylius_um_admin_um.yaml"

jms_serializer:
    metadata:
        directories:
            blackowl-sylius-um:
                namespace_prefix: "Blackowl\\SyliusUmPlugin\\Entity"
                path: "@BlackowlSyliusUmPlugin/Resources/config/serializer"
