BlackOwl\SyliusSupplierPlugin\Model\Supplier:
    exclusion_policy: ALL
    xml_root_name: supplier
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        address:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        email:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        tel:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        vat:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
       
    relations:
        -   rel: self
            href:
                route: blackowl_sylius_supplier_admin_api_supplier_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
        -   rel: products
            href:
                route: blackowl_sylius_supplier_admin_api_supplier_product_index
                parameters:
                    code: expr(object.getCode())
                    version: 1
            exclusion:
                groups: [Default, Detailed]
