Blackowl\SyliusUmPlugin\Entity\ProductUm:
    exclusion_policy: ALL
    xml_root_name: um
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
    relations:
        -   rel: self
            href:
                route: blackowl_sylius_um_admin_api_um_show
                parameters:
                    code: expr(object.getCode())
                    version: 1
        -   rel: products
            href:
                route: blackowl_sylius_um_admin_api_um_product_index
                parameters:
                    code: expr(object.getCode())
                    version: 1
            exclusion:
                groups: [Default, Detailed]
